# Generated by Django 6.0 on 2025-12-13 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_at', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brend', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rasmlar/')),
                ('desc', models.CharField(max_length=255)),
                ('xotira', models.IntegerField(default=0)),
                ('ram_xotira', models.IntegerField(default=0)),
                ('ish_chiq_yil', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('yaroqlilik_muddati', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefon.mahsulotlar')),
            ],
        ),
    ]
