# Generated by Django 6.0 on 2025-12-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mahsulotlar',
            new_name='Mahsulotlar_brendi',
        ),
        migrations.RenameField(
            model_name='telefon',
            old_name='brend',
            new_name='turi',
        ),
    ]
